### PR TITLE
Bump alpine version to 3.9

### PR DESCRIPTION
**Pull request by otto-md**
I hope this works, alpine 3.9 has been out for a while now.

### CODE REVIEW

**Comment by otto-md** [comment]
Hey @ali-ince, any updates regarding support for Alpine 3.9?

**Comment by ali-ince** [comment]
Hi @otto-md,

The upcoming patch release will include a binary built for alpine-3.9 as well as alpine-3.8.

Thanks for reporting this issue.

**Comment by otto-md** [comment]
Thats great news. Thanks!

**Comment by otto-md** [comment]
Do you know when the next release is happening? Is it days or weeks or months away?

**Comment by ali-ince** [comment]
It just happened @otto-md. You can find binaries under latest release artifacts on the releases page.

**Pull request closed without merging**
